spring:
  application:
    title: otus-homework
    version: hw10-rest-ajax
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true